companieshouse/certificates.orders.web.ch.gov.uk

- .gitignore
- Makefile
- README.md
- dist/.gitignore
- gulpfile.js
- package-lock.json
- package.json
- src/app.ts
- src/handlers/home.ts
- src/handlers/index.ts
- src/routers/index.ts
- src/server.ts
- src/test/handlers/home.spec.ts
- src/test/jest.config.js
- src/test/setup.ts
- src/views/base.html
- src/views/index.html
- static/_variables.scss
- static/app.scss
- tsconfig.json
- tslint.json
> Copied node web starter project as initial commit

- README.md
- package-lock.json
- src/app.ts
Removed vulnerabilities, updated port and updated README.
Resolves: PCI-499
> Removed vulnerabilities, updated port and updated README

- src/app.ts
- src/session/config.ts
- src/views/layout.html
Enable Piwik for certificates order web node front end
Resolves: PCI-622
> Add piwik to cert web

- src/test/setup.ts
> add-piwik-test-values

- src/app.ts
- src/controllers/order.details.controller.ts
- src/model/error.messages.ts
- src/model/page.urls.ts
- src/model/template.paths.ts
- src/routers/routers.ts
- src/test/controllers/order-details.controller.spec.unit.ts
- src/views/good-standing.html
- src/views/index.html
- src/views/layout.html
- src/views/order-details.html
Add order details page
Add controller
Add unit test
Update links for a correct user journey
Resolves: PCI-549
> Pci 549 enter the name screen

- src/controllers/order.details.controller.ts
- src/test/controllers/order.details.controller.spec.unit.ts
- src/test/utils/char.set.spec.unit.ts
- src/utils/char-set.ts
Split out validation function
Resolves PCI-549
> Add unit test

- src/views/layout.html
Update service name
Resolves: PCI-549
> update service name

- src/views/index.html
Updated text to match prototype
Resolves: PCI-633
> update page with text

- src/views/good-standing.html
update radio buttons to inline
update text format to match prototype
Resolves: PCI-555
> update radio buttons to inline

- src/controllers/collection.controller.ts
- src/model/error.messages.ts
- src/model/page.urls.ts
- src/model/template.paths.ts
- src/routers/routers.ts
- src/test/controllers/collection.controller.spec.unit.ts
- src/views/collection.html
Add collection controller
Add collection to router
Add collection unit tests
Add validation to collection office
Update good standing link to collection page
Resolves: PCI-556
> Add collection web page

- src/model/error.messages.ts
- src/test/controllers/collection.controller.spec.unit.ts
Update validation error text
Update error text expected in test
Resolves: PCI-556
> Update validation error text

- src/controllers/good.standing.controller.ts
- src/test/controllers/good.standing.controller.spec.unit.ts
- src/views/good-standing.html
Add error message in browser tab when validation error occurs
Resolves: PCI-555
> clean code for order a certificate

- src/model/error.messages.ts
> Update validation error title text

- static/footer.scss
Add blue banner to footer 
Underline footer links
Resolves: PCI-699
> Add blue banner to footer Underline footer links

- src/views/components/header/template.njk
Added alt text to image.
resolves: PCI-750
> Added alt text to image

- routes.yaml
- src/app.ts
- src/controllers/home.controller.ts
- src/controllers/home.ts
- src/model/page.urls.ts
- src/routers/routers.ts
- src/test/controllers/collection.controller.spec.unit.ts
- src/test/controllers/good.standing.controller.spec.unit.ts
- src/test/controllers/home.spec.unit.ts
- src/test/controllers/order.details.controller.spec.unit.ts
- src/views/index.html
- src/views/layout.html
- src/views/order-details.html
Add function to capture url from url
Update URIs to display company number
Update templates to new urls
Update tests with new urls
Update routes.yaml
Resolves: CGI-792
> Capture company number from ch.gov to be used in certificate orders web

- src/controllers/index.ts
> fix home controller

- src/model/page.urls.ts
- src/views/index.html
Update back link url to include company in context company number 
Resolve linting
Resolves GCI-683
> Update back link url to include company in context company number 

- src/app.ts
> update page urls import

- src/controllers/order.details.controller.ts
> Add hard coded values to certificate item

- src/controllers/order.details.controller.ts
> hard code collection location

- src/views/index.html
> update displayed text to match mvp proto

- src/views/index.html
Updated text in the fee section to match mvp prototype
Resolves: GCI-835
> update fee text

- src/controllers/certificate.options.controller.ts
- src/controllers/home.controller.ts
- src/middleware/auth.middleware.ts
- src/model/page.urls.ts
- src/model/template.paths.ts
- src/routers/routers.ts
- src/test/controllers/certificate.options.spec.unit.ts
- src/test/middleware/auth.middleware.spec.unit.ts
- src/views/certificate-options.html
- src/views/index.html
- src/views/order-details.html
Add certificate options controller
Add certificate options to router
Add certificate options unit test
Update web journey screen order
Update auth middleware to use certificate options instead of user details page
Resolves: GCI-934
> Add certificate options screen to web journey

- src/routers/routers.ts
- src/test/controllers/certificate.options.spec.integration.ts
- src/test/controllers/check.details.controller.spec.integration.ts
- src/views/check-details.html
- src/views/layout.html
> Create skeleton check your order details page with dummy data

- src/controllers/certificate.options.controller.ts
- src/test/controllers/certificate.options.spec.unit.ts
added case if options are undefined
resolves: GCI-570
> added case if options are undefined

- src/controllers/delivery.details.controller.ts
- src/model/error.messages.ts
- src/test/controllers/delivery.details.controller.spec.integration.ts
Add validation either postcode or county must be input
Add test to cover either postcode or county input
> Gci 1013 address validation

- src/controllers/delivery.details.controller.ts
- src/model/error.messages.ts
Added validation for postcode and county error messages
Resolves: GCI-1013
> add validation for county and postcode fields

- package.json
- src/client/api.client.ts
- src/controllers/certificate.options.controller.ts
- src/controllers/check.details.controller.ts
- src/middleware/certificate.middleware.ts
- src/routers/routers.ts
- src/session/config.ts
- src/test/controllers/check.details.controller.spec.integration.ts
- src/test/setup.ts
- src/views/check-details.html
Add item to basket
Redirect to basket url
Resolves: GCI-586
> redirect to orders web

- src/controllers/certificate.type.controller.ts
> Update certificate item resource to reflect postal delivery

- package.json
- src/client/api.client.ts
> Bump sdk version Update Basket type import

- package.json
- src/client/api.client.ts
- src/controllers/delivery.details.controller.ts
- src/routers/routers.ts
- src/test/client/apiclient.spec.unit.ts
- src/test/controllers/check.details.controller.spec.integration.ts
- src/test/controllers/delivery.details.controller.spec.integration.ts
Add GET and PATCH basket
Render delivery details page using GET
PATCH basket using input from delivery details page
Update delivery details router
Add integration tests
Resolve: GCI-1010
> Gci 1010 patch delivery details

- src/controllers/delivery.details.controller.ts
- src/model/error.messages.ts
- src/test/controllers/delivery.details.controller.spec.integration.ts
Validate country to be a required field 
Update test
Resolves: GCI-1084
> Validate country to be a required field Update test

- src/controllers/delivery.details.controller.ts
> add company number to render delivery details page

- package-lock.json
- src/controllers/check.details.controller.ts
- src/routers/routers.ts
- src/test/controllers/check.details.controller.spec.integration.ts
- src/test/controllers/check.details.controller.spec.unit.ts
- src/views/check-details.html
> Add functionality to display the correct information on check details screen

- src/views/index.html
- src/views/layout.html
> update text on start now page

- src/views/layout.html
Add image to titlebar in certificates service
Resolves: GCI-1105
> Add favicon to title bar for certificates service

- package-lock.json
- package.json
- src/app.ts
- src/bin/www.ts
- src/client/api.client.ts
- src/config/config.ts
- src/controllers/certificate.options.controller.ts
- src/controllers/certificate.type.controller.ts
- src/controllers/check.details.controller.ts
- src/controllers/delivery.details.controller.ts
- src/controllers/home.controller.ts
- src/middleware/auth.middleware.ts
- src/middleware/certificate.auth.middleware.ts
- src/routers/routers.ts
- src/session/helper.ts
- src/test/controllers/certificate.options.spec.integration.ts
- src/test/controllers/certificate.options.spec.unit.ts
- src/test/controllers/check.details.controller.spec.integration.ts
- src/test/controllers/delivery.details.controller.spec.integration.ts
- src/test/controllers/home.controller.spec.integration.ts
- src/test/middleware/auth.middleware.spec.integration.ts
- src/test/middleware/auth.middleware.spec.unit.ts
- src/test/middleware/certificate.auth.middleware.spec.unit.ts
- src/test/utils/char.set.spec.unit.ts
- tsconfig.json
Update module imports Move config file
update express types module
update node session handler
implement session handler changes
update unit and integration tests
import ch logging
implement ch logging
resolve linting
add error log messages
Resolves: GCI-945
> Gci 945 add logging and cleanup

- src/client/api.client.ts
- src/controllers/certificate.options.controller.ts
- src/controllers/delivery.details.controller.ts
- src/test/controllers/certificate.options.spec.integration.ts
- src/test/controllers/delivery.details.controller.spec.integration.ts
Fix company number not showing in logs 
Update patch status
> Resolve log issues

- src/client/api.client.ts
- src/controllers/certificate.options.controller.ts
Removed unused get company profile method
Resolves: GCI-945
> add further logging msgs

- src/middleware/auth.middleware.ts
- src/middleware/certificate.auth.middleware.ts
add unauthorized access log message
resolves: GCI-945
> add unauthorized log message

- src/views/certificate-options.html
> Update company objects text

- package-lock.json
- package.json
> bump ch structured logging version to use GMT time

- package-lock.json
- package.json
- src/app.ts
- src/config/config.ts
Session handler latest version now logs correct timestamp
Resolves: GCI-1184
> bump session handler module version

- src/controllers/certificates/check.details.controller.ts
- src/views/certificates/index.html
- test/controller/certificates/check.details.controller.unit.test.ts
Copy changes clarifying certificate dispatch time
> Feature: GCI-1186: Copy changes

- src/controllers/certified-copies/home.controller.ts
- src/views/certified-copies/index.html
- test/controller/certificates/check.details.controller.integration.test.ts
- test/controller/certificates/check.details.controller.unit.test.ts
- test/controller/certificates/delivery.details.controller.integration.test.ts
- test/controller/certified-copies/home.controller.integration.test.ts
Add a start page to the certified copies user journey
> Feature/GCI-860: Certified copies start page

- src/app.ts
- src/controllers/certified-copies/check.details.controller.ts
- src/controllers/certified-copies/delivery.details.controller.ts
- src/controllers/certified-copies/home.controller.ts
- src/middleware/certified-copies/auth.middleware.ts
- src/model/page.urls.ts
- src/routers/certified-copies/routers.ts
- test/middleware/auth.middleware.integration.test.ts
- test/middleware/certified-copies/auth.middleware.unit.test.ts
Ensure a user is signed in to a certified copies journey.
> Feature/GCI-861: Add authentication to certified-copies journeys

- src/app.ts
There were some linting errors that slipped through the last PR.. this fixes them
> Chore: Fix linting errors

- src/app.ts
- src/views/layout.html
Add link to correct service in the header..
> Fix/GCI-860: Link to correct service in header

- src/views/layout.html
> Certificates Web - Add accessibility statement link to footer

- package.json
- src/controllers/certified-copies/check.details.controller.ts
- src/views/certified-copies/check-details.html
- test/controller/certified-copies/check.details.controller.integration.test.ts
Adds skeleton page for check-details for certified-copies
> Feature/GCI-1228: Add skeleton page for check-details

- src/views/layout.html
> Remove accessibility link until audit has been completed

- src/app.ts
- src/controllers/certificates/delivery.details.controller.ts
- src/controllers/certificates/options.controller.ts
- src/controllers/certified-copies/delivery.details.controller.ts
- src/model/template.paths.ts
- src/routers/certified-copies/routers.ts
- src/utils/delivery-details-validation.ts
- src/views/delivery-details.html
- test/controller/certified-copies/delivery.details.controller.integration.test.ts
extract delivery details validation to common file
refactor certificates delivery details controller to use common validation
create certs copies controller
change back link on delivery details template to be dynamic based on the service user is in
extract delivery details template as now a common file
add delivery details integration test
Resolves: GCI-907
> Gci 907 delivery details page cert copies

- src/controllers/certified-copies/delivery.details.controller.ts
- test/controller/certified-copies/delivery.details.controller.integration.test.ts
patch delivery details for certified copies
resolves: GCI-1050
> patch delivery details for certified copies

- src/client/api.client.ts
- src/config/config.ts
- src/controllers/certificates/home.controller.ts
- test/client/api.client.unit.test.ts
- test/controller/certificates/home.controller.integration.test.ts
- test/setup.ts
add get company profile function to api client
add logic to home controller to check company type
add get company profile unit test
update home controller integration test
Resolves: GCI-1278
> Implement company type check for access to certs web

- package-lock.json
- package.json
- src/client/api.client.ts
- src/controllers/certified-copies/delivery.details.controller.ts
- test/client/api.client.unit.test.ts
- test/controller/certified-copies/delivery.details.controller.integration.test.ts
add get certified copy item to api client
implement get certified copy in delivery details controller
update node sdk dependency
update unit and integration tests
Resolves: GCI-1251
> Add functionality to delivery details page for certified copies

- src/views/certified-copies/index.html
Jira story: GCI-1285 - Update 'Order a certified document' page
> Changing the Fee text in the order a certified document page

- package-lock.json
- package.json
- src/controllers/certified-copies/home.controller.ts
- test/client/api.client.unit.test.ts
- test/controller/certificates/home.controller.integration.test.ts
- test/controller/certified-copies/home.controller.integration.test.ts
add logic to home controller to check if company is allowed to order a cert copy
display error page if user tries to access the service but company does not meet requirements
update tests
update sdk dependency
Resolves: GCI-1284
> Implement company type check  for cert copies and display error page

- src/views/certificates/options.html
Added changes to record the additional information selected when ordering a certificate.
Jira ticket GCI-1291
> Amendments made to record the checkbox selection(s) made in piwik

- Makefile
added api-enumerations to build step
resolves: GCI-1306
> added api-enumerations to build step

- .mocharc.json
- src/controllers/certified-copies/check.details.controller.ts
- src/routers/certified-copies/routers.ts
- src/views/certified-copies/check-details.html
- test/controller/certified-copies/check.details.controller.integration.test.ts
added payment functionality to certified docs
resolves: GCI-1274
> added payment functionality to certified docs

- src/views/certified-copies/check-details.html
> Add link functionality to certified docs check your order details page

- src/views/certified-copies/check-details.html
> Text change, redirecting to right page  and accessibility issue fixed

- src/views/certified-copies/check-details.html
> Change the tab display name of the Check yoru order details page

- src/views/certified-copies/check-details.html
Amended page to have Your document details instead of Document details.
GCI-1353
> Page text amendment

- src/views/certified-copies/check-details.html
Reverted text to be Document details instead of Your document details
GCI-1353
> Reverted previous text change

- src/app.ts
- src/config/config.ts
- src/views/certificates/index.html
- src/views/certified-copies/index.html
- start.sh
- test/setup.ts
Amendments made to add a PIWIK goal to the start button of certificates and certified copies web journey.
GCI-1351
> Add piwik goal to start buttons

- package-lock.json
- package.json
- src/controllers/certified-copies/check.details.controller.ts
- src/utils/check.details.utils.ts
- src/views/certified-copies/check-details.html
- test/client/api.client.unit.test.ts
- test/controller/certified-copies/check.details.controller.integration.test.ts
- test/controller/certified-copies/check.details.controller.unit.test.ts
- test/utils/check.details.utils.unit.test.ts
Update check details screen to include the correct fees and the total cost.
Resolves: GCI-1334
> Add fees and total cost to check details screen

- package-lock.json
- package.json
- src/controllers/certified-copies/check.details.controller.ts
- src/utils/check.details.utils.ts
- test/client/api.client.unit.test.ts
- test/controller/certified-copies/check.details.controller.integration.test.ts
- test/controller/certified-copies/check.details.controller.unit.test.ts
- test/utils/check.details.utils.unit.test.ts
> Update total costs to point at new total_item_costs field

- src/views/certificates/index.html
- src/views/certified-copies/index.html
Amendments made to include the PIWIK goal ID on the start buttons for… certificates and certified-copies.
Jira ticket GCI-1351
> PIWIK goal ID's added to certificates and certified-copies

- package-lock.json
Updates versions of `bl` and `lodash`
> package version updates to fix security vulnerability

- package-lock.json
- package.json
- src/app.ts
- src/client/api.client.ts
- src/controllers/scud/create.scud.item.controller.ts
- src/model/page.urls.ts
- src/routers/scud/routers.ts
- test/client/api.client.unit.test.ts
- test/controller/scud/create.scud.item.controller.integration.test.ts
Bump sdk version
Add post for scud item
Add create scud
Add scud create route
Add unit and integration test
Resolves: GCI-1398
> Add create scud item to certs web

- package-lock.json
- package.json
- src/client/api.client.ts
- src/controllers/missing-image-delivery/create.missing.image.delivery.item.controller.ts
- test/client/api.client.unit.test.ts
- test/controller/missing-image-delivery/create.scud.item.controller.integration.test.ts
> Update sdk related code to reflect change to MID

- src/views/missing-image-delivery/check-details.html
- test/controller/missing-image-delivery/check.details.controller.integration.test.ts
GCI-221 Simple text change on skeleton check order details of MID document
> Change skeleton order details texts

- src/controllers/missing-image-delivery/check.details.controller.ts
- src/routers/missing-image-delivery/routers.ts
- src/views/missing-image-delivery/check-details.html
- test/controller/missing-image-delivery/check.details.controller.integration.test.ts
add mid to basket and redirect to orders web
resolves: GCI-1379
> add mid to basket and redirect to orders web

- src/controllers/certificates/home.controller.ts
- src/views/certificates/index.html
- test/__mocks__/certificates.mocks.ts
- test/controller/certificates/home.controller.integration.test.ts
Update Order a certificate page for dissolved certificates
> Update Order a certificate page for dissolved certificates

- routes.yaml
- src/model/page.urls.ts
- test/controller/missing-image-delivery/create.scud.item.controller.integration.test.ts
- test/middleware/missing-image-delivery/auth.middleware.unit.test.ts
> Change the URL to plural and amend the unit tests

- test/controller/missing-image-delivery/create.missing.image.delivery.item.controller.integration.test.ts
Update test url for MID due to change in url
Resolves: GCI-1516
> Gci 1516 create dissolved certificate

- src/controllers/certificates/check.details.controller.ts
- src/controllers/certificates/delivery.details.controller.ts
- src/controllers/certificates/home.controller.ts
- src/views/certificates/check-details.html
- test/__mocks__/certificates.mocks.ts
- test/controller/certificates/check.details.controller.integration.test.ts
- test/controller/certificates/home.controller.integration.test.ts
Change link location on delivery details page
> Gci 879 chs dissolutions

- test/setup.ts
add test piwik goal id for dissolved certs
Resolves: GCI-1483
> add test piwik goal id for dissolved certs

- routes.yaml
- src/app.ts
- src/controllers/certificates/check.details.controller.ts
- src/controllers/certificates/delivery.details.controller.ts
- src/controllers/certificates/home.controller.ts
- src/controllers/certificates/type.controller.ts
- src/middleware/certificates/auth.middleware.ts
- src/model/page.urls.ts
- src/routers/certificates/routers.ts
- src/utils/service.url.utils.ts
- test/controller/certificates/type.controller.integration.test.ts
- test/middleware/certificates/auth.middleware.unit.test.ts
- test/utils/service.url.utils.test.ts
add dissolved certs routes
add auth to dissolved certs routes
update controllers to pass correct urls
add service url util
add service url util test
updated controller tests
Resolves: GCI-1545
> Update certs web to use /orderable/dissolved-certificates url for dissolved journey

- src/controllers/certificates/check.details.controller.ts
Revert setting itemUri within the check details controller 
Resolves: GCI-1545
> update itemUri in check details controller

- src/views/missing-image-deliveries/index.html
Updated start now page text for MID journey
Resolves: GCI-1611
> update text on start now page for MID

- src/views/missing-image-deliveries/index.html
Added space in text on page
Resolves GCI-1611
> add space in text

- src/views/missing-image-deliveries/check-details.html
update text on check details page for mid to match prototype
Resolves: GCI-1637
> update text on check details page for mid

- src/views/missing-image-deliveries/check-details.html
> update text on check details page

- .dockerignore
- Dockerfile
Add Dockerfile and .dockerignore files
> Add Dockerfile and .dockerignore files

- package-lock.json
- package.json
bump node session handler version
Resolves: BI-6119
> bump node session handler version

- src/views/certificates/options.html
Made the text change to registered office address hint
Resolves: BI-6153
> Text change to registered office address hint

- src/views/certificates/registered-office-options.html
Changed the fields to not contain whitespace and be able to pass testing
Resolves: BI-6154
> Changed the idPrefixed and name

- src/controllers/certificates/check.details.controller.ts
- src/controllers/certificates/options.controller.ts
- src/views/certificates/check-details.html
- test/controller/certificates/check.details.controller.integration.test.ts
- test/controller/certificates/check.details.controller.unit.test.ts
Changed the page layout of check order details & updated integration and unit tests
Resolves: BI-6029
> Changed the page layout of check order details

- src/controllers/certificates/options.controller.ts
- src/routers/certificates/routers.ts
- src/views/certificates/registered-office-options.html
- test/controller/certificates/options.controller.integration.test.ts
- test/controller/certificates/options.controller.unit.test.ts
This PR adds the functionality to move to the registered office address screen, additional PR will be raised for validation
Resolves: BI-6024
> BI-6024 registered office options functionality

- src/routers/certificates/routers.ts
Code meant for another PR accidentally commited removed
> Fix code that is meant for the validation PR

- src/controllers/certificates/options.controller.ts
- src/controllers/certificates/registered.office.options.controller.ts
- src/routers/certificates/routers.ts
- src/views/certificates/registered-office-options.html
- test/controller/certificates/registered.office.options.integration.test.ts
- Fix no option selected issue
- Fix back button
- Add basic POST to unblock other developers
> Fix issue where no option selected breaks build and fix back button

- src/views/certificates/check-details.html
Changed the change cert options url to take the user back to the certificate options page.
Resolves: BI-6029
> Changed the change cert options url

- src/views/certificates/registered-office-options.html
Added piwik recording of selected registered office address options
BI-6025
> Added piwik recording of selected registered office address options.

- src/controllers/certificates/registered.office.options.controller.ts
Added a fix to ensure service url is available on register office page
> Fix service URL

- src/controllers/certificates/delivery.details.controller.ts
- src/controllers/certificates/options.controller.ts
- src/controllers/certificates/registered.office.options.controller.ts
- src/validation/certificates/registered.office.options.validation.ts
- src/views/certificates/registered-office-options.html
- test/controller/certificates/registered.office.options.integration.test.ts
- test/controller/certificates/registered.office.options.unit.test.ts
Patches the option selected on the registered office options page to the certificate item
Resolves: BI-6027
> add patch cert item to reg office option page

- src/controllers/certificates/check.details.controller.ts
- src/controllers/certificates/registered.office.options.controller.ts
- src/views/certificates/check-details.html
- test/controller/certificates/check.details.controller.integration.test.ts
- test/controller/certificates/check.details.controller.unit.test.ts
add logic to output reg office address option on check details page
Resolves: BI-6158
> add logic to output reg office address option on check details page

- src/views/certificates/options.html
Changed the text for directors options
Resolves: BI-6163
> Changed the text for directors options

- src/controllers/certificates/director.options.controller.ts
- src/model/page.urls.ts
- src/model/template.paths.ts
- src/routers/certificates/routers.ts
- src/views/certificates/director-options.html
- test/controller/certificates/director.options.controller.integration.test.ts
Added skeleton page for director options
Jira Ticket BI-6164
> Added skeleton page for director options

- src/views/certificates/director-options.html
Added piwik reporting to director options checkboxes
Jira Ticket : BI-6022
> Added piwik reporting to director options checkboxes

- src/controllers/certificates/registered.office.options.controller.ts
- src/views/certificates/registered-office-options.html
pass reg office option object to template to render previously selected option
Resolves: BI-6395
> Retains previously selected option for reg office address

- src/views/certificates/options.html
Change to check the object rather than a specific value
Resolves: BI-6395
> update template to check generic reg office selection

- src/views/certificates/check-details.html
> Fixed spelling mistake that stopped dissolved change link working

- src/views/certificates/options.html
Reverted text change for the director details hint
Jira Ticket BI-6416
> Reverted text change for the director details hint

- src/views/certificates/options.html
Changed director details text
Jira Ticket : BI-6163
> Changed director details text

- src/views/certificates/secretary-options.html
Added PIWIK reporting for secretary options
Jira Ticket : BI-6205
> Added PIWIK reporting for secretary options

- src/controllers/certificates/delivery.details.controller.ts
- test/controller/certificates/delivery.details.controller.integration.test.ts
- test/controller/certificates/delivery.details.controller.unit.test.ts
Add routing for the back button so that it returns the user to the correct page
Resolves: BI-6020
> BI-6020 - Add routing for the back button delivery details

- package-lock.json
- package.json
- src/controllers/certificates/director.options.controller.ts
Set default dob value for directors to null to allow a user to change their option which was previously retaining the wrong dob information.
Resolves: BI-6019
> bump sdk version set default dob to null

- src/controllers/certificates/check.details.controller.ts
- src/controllers/certificates/delivery.details.controller.ts
- src/controllers/certificates/director.options.controller.ts
- src/views/certificates/check-details.html
- test/controller/certificates/check.details.controller.integration.test.ts
- test/controller/certificates/check.details.controller.unit.test.ts
- Add mappings to correctly display director options
- Increase test coverage
- Remove unused `mapIncludedOnCertificate` and tests 
Resolves: BI-6017
> BI-6017 - Update check details to correctly map director options

- src/views/certificates/options.html
Amended hint text for secretaries
Jira Ticket BI-6196
> Amended hint text for secretaries

- src/controllers/certificates/director.options.controller.ts
- src/controllers/certificates/options.controller.ts
- src/controllers/certificates/registered.office.options.controller.ts
- src/controllers/certificates/secretary.options.controller.ts
- src/routers/certificates/routers.ts
- src/views/certificates/secretary-options.html
- test/controller/certificates/director.options.controller.integration.test.ts
- test/controller/certificates/options.controller.integration.test.ts
- test/controller/certificates/registered.office.options.integration.test.ts
- test/controller/certificates/secretary.options.controller.integration.test.ts
- test/controller/certificates/secretary.options.controller.unit.test.ts
add post to secretary controller and router
add logic for backlink and redirect for in secretary controller
update other controllers to redirect to secretary page dependent on options selected
add integration tests for routing through app when secretary option selected
add unit test for secretary backlink function
fix linting issues
Resolves: BI-6198
> add functionality for secretary page

- src/controllers/certificates/delivery.details.controller.ts
- test/controller/certificates/delivery.details.controller.integration.test.ts
- test/controller/certificates/delivery.details.controller.unit.test.ts
> BI-6204 - Update delivery details backlint to include secretary options page

- src/controllers/certificates/director.options.controller.ts
- src/controllers/certificates/options.controller.ts
- src/controllers/certificates/secretary.options.controller.ts
- src/views/certificates/secretary-options.html
- test/controller/certificates/secretary.options.controller.integration.test.ts
- test/controller/certificates/secretary.options.controller.unit.test.ts
Patches the selected options on the secretary options page to the certificate item.
Resolves: BI-6203
> implement certificate item patch into secretary options page

- src/controllers/certificates/check.details.controller.ts
- src/views/certificates/check-details.html
- test/controller/certificates/check.details.controller.integration.test.ts
- test/controller/certificates/check.details.controller.unit.test.ts
- test/controller/certificates/secretary.options.controller.integration.test.ts
> BI-6220 update check details secretaries

- src/views/certified-copies/index.html
Small grammatical text change on start now page cert copies
Resolves: BI-7072
> amend text start now page

- src/views/certified-copies/index.html
Small text change on start now page in cert copies
Resolves: BI-7072
> update text on start now page cert copies

- src/views/certificates/index.html
Added piwik reporting on link for certified copies from the certificates start page
Jira Ticket BI-7852
> Added piwik for certified-copies link

- src/views/certified-copies/index.html
Added piwik link for certificates from the certified copies start page
Jira Ticket BI-7853
> Added piwik link for certificates

- src/client/api.client.ts
- src/controllers/certificates/home.controller.ts
- src/controllers/certificates/type.controller.ts
- src/model/page.urls.ts
Adds additional debug logging to Certificates Orders Web
> Add additional debug logging to certificates orders web

- src/views/layout.html
Add meta tag to prevent services from being indexed by search engines
**Resolves :** 
- GCI-1846
- GCI-1847
- GCI-1848
> Add meta tag to prevent services from being indexed by search engines

- src/controllers/certificates/check.details.controller.ts
- test/controller/certificates/check.details.controller.integration.test.ts
- test/controller/certificates/check.details.controller.unit.test.ts
removed the <br> from the directors and secretaries. fixed tests
> BI-7727-fix-cross-scripting

- src/views/missing-image-deliveries/index.html
- test/controller/missing-image-deliveries/home.controller.integration.test.ts
update wording for mid banner update test
Resolves GCI-1854
> update wording for mid banner update test

- .dockerignore
* Fix an issue causing static content to be omitted from the Docker
container image.
> Include static directory in Docker build

- src/views/components/footer/template.njk
> update built by footer link

- package-lock.json
- package.json
- src/controllers/certificates/llp-certificates/type.controller.ts
- src/controllers/certificates/lp-certificates/type.controller.ts
- src/controllers/certificates/model/CertificateItemFactory.ts
- src/controllers/certificates/model/CertificateType.ts
- src/controllers/certificates/model/CompanyStatus.ts
- src/views/certificates/llp-certificates/index.html
- src/views/certificates/lp-certificates/index.html
- test/__mocks__/certificates.mocks.ts
- test/__mocks__/company.profile.mocks.ts
- test/client/api.client.unit.test.ts
- test/controller/certificates/check.details.controller.integration.test.ts
- test/controller/certificates/check.details.controller.unit.test.ts
- test/controller/certificates/model/CertificateItemFactory.test.ts
- test/controller/certificates/secretary.options.controller.unit.test.ts
- test/controller/certificates/type.controller.integration.test.ts
- test/controller/certified-copies/home.controller.integration.test.ts
- test/utils/check.details.utils.unit.test.ts
* Add factory to create CertificateItemPostRequest objects using company profile properties
* Add enum types for CertificateType and CompanyStatus
* Refactor placeholder type.controllers to use new item request factory and rationalise sequence logic
* Updated placeholder landing page templates with correct certificate option text
> BI-8703 Add new landing pages for LP & LLP certificate orders

- package.json
- src/controllers/certificates/check.details.controller.ts
- src/controllers/certificates/llp-certificates/options.controller.ts
- src/controllers/certificates/lp-certificates/options.controller.ts
- src/controllers/certificates/secretary.options.controller.ts
- src/views/certificates/llp-certificates/options.html
- src/views/certificates/lp-certificates/options.html
- test/__mocks__/certificates.mocks.ts
- test/__mocks__/company.profile.mocks.ts
- test/client/api.client.unit.test.ts
- test/controller/certificates/check.details.controller.unit.test.ts
- test/controller/certificates/llp-certificates/options.controller.integration.test.ts
- test/controller/certificates/llp-certificates/options.controller.unit.test.ts
- test/controller/certificates/lp-certificates/options.controller.integration.test.ts
- test/controller/certificates/lp-certificates/options.controller.unit.test.ts
- test/controller/certificates/secretary.options.controller.unit.test.ts
- test/utils/check.details.utils.unit.test.ts
* For LLPs, designated members and members will be displayed instead of
directors and secretaries.
* For Limited Partnerships, principle place of business, general
partners and limited partners will be displayed instead of registered
office address, directors and secretaries.
* Remove ch-sdk-node dependency and usages from project.
* Update unit tests to reflect API changes.
Resolves:
[BI-8720](https://companieshouse.atlassian.net/browse/BI-8720)
> BI-8720 Dynamic certificate options page for LLPs and LPs

- src/controllers/certificates/lp-certificates/options.controller.ts
- src/views/certificates/llp-certificates/members-options.html
Implement general nature of business item options
- Fix form field property naming
- Map form field in controller
> BI-8728 Implement general nature of business item options

- src/views/certificates/llp-certificates/check-details.html
- src/views/certificates/lp-certificates/check-details.html
- Use consistent spelling and grammar for officer details
Resolves [BI-9155 (Incorrect Officer Details Wording - Across LLP and LP journey)](https://companieshouse.atlassian.net/browse/BI-9155)
> BI-9155 Change wording for officer details

- src/views/certificates/lp-certificates/options.html
- Corrected values of checked keys: generalPartnerDetails, limitedPartnerDetails, includeGeneralNatureOfBusinessInformation
Resolves: [BI-9160: Retaining users choices across the LP journey](https://companieshouse.atlassian.net/browse/BI-9160)
> BI-9160 Fix values of checked key within items

- package-lock.json
- src/middleware/certificates/auth.middleware.ts
- Reinstate package-lock.json
- Remove unused import
> BI-9193 feature flags for LP & LLP  journeys

- src/views/certificates/llp-certificates/options.html
- src/views/certificates/lp-certificates/options.html
* Use of correct spelling for options and hint text
Resolves [BI-9434](https://companieshouse.atlassian.net/browse/BI-9434)
> BI-9434 Amend changes to LP and LLP option pages

- src/controllers/certificates/OptionFilter.ts
- src/controllers/certificates/home.controller.ts
- src/controllers/certificates/model/CompanyStatus.ts
- src/views/certificates/index.html
- src/views/certificates/llp-certificates/index.html
- test/__mocks__/certificates.mocks.ts
- test/controller/certificates/home.controller.integration.test.ts
- Implements conditional logic to display liquidators details 
- option on landing page for companies in liquidation
[BI-8879](https://companieshouse.atlassian.net/browse/BI-8879)
> BI-8879 Liquidators details landing page

- package-lock.json
- package.json
- src/controllers/certificates/llp-certificates/options.controller.ts
- src/controllers/certificates/options.controller.ts
- src/views/certificates/llp-certificates/options.html
- src/views/certificates/options.html
- test/client/api.client.unit.test.ts
- test/controller/certificates/check.details.controller.unit.test.ts
- test/controller/certificates/llp-certificates/options.controller.integration.test.ts
- test/controller/certificates/llp-certificates/options.controller.unit.test.ts
- test/controller/certificates/options.controller.integration.test.ts
- test/controller/certificates/options.controller.unit.test.ts
- test/utils/check.details.utils.unit.test.ts
* Filter good standing option if company is in liquidation.
* Filter liquidators option if company is active.
* Tested locally; working.
Resolves:
[BI-8848](https://companieshouse.atlassian.net/browse/BI-8848)
> BI-8848 Implement option filter on cert options page

- src/controllers/certificates/llp-certificates/CompanyStatusHelper.ts
- src/controllers/certificates/llp-certificates/type.controller.ts
- src/controllers/certificates/model/CertificateItemFactory.ts
* Correctly map liquidation company status to certificate type
* Refactor company status to certificate type and company status to
redirect path using a helper class
Related: [BI-9647 Automation tests](https://companieshouse.atlassian.net/browse/BI-9647)
> BI-9647 Fix incorrect certificate type mapping

- src/controllers/certificates/delivery.details.controller.ts
- src/controllers/certificates/llp-certificates/delivery.details.controller.ts
- src/controllers/certificates/lp-certificates/delivery.details.controller.ts
* Delivery method and delivery timescale fields have been removed from initial request.
Related:
[BI-9890](https://companieshouse.atlassian.net/browse/BI-9890)
> Set delivery method, timescale on delivery details

- src/controllers/certificates/check.details.controller.ts
- src/controllers/certificates/llp-certificates/check.details.controller.ts
- src/views/certificates/check-details.html
- src/views/certificates/llp-certificates/check-details.html
- test/controller/certificates/check.details.controller.integration.test.ts
- test/controller/certificates/llp-certificates/check.details.controller.integration.test.ts
* Set liquidators' details field to display if company is in
liquidation.
* Set liquidators' details to Yes if liquidators_details .
include_basic_information == true.
Resolves:
[BI-8849](https://companieshouse.atlassian.net/browse/BI-8849)
> BI-8849 Handle liquidated companies on check details page

- src/views/certificates/check-details.html
- src/views/certificates/llp-certificates/check-details.html
- src/views/certificates/lp-certificates/check-details.html
* Fix missing id on submit button.
* Add id to page headings and restart link.
> BI-9651 Add ids to check-details page

- src/views/components/footer/template.njk
BI-9824 Direct users to GOV.UK contact page - Certified Copies
> Direct users to GOV.UK contact page - Certified Copies

- src/client/api.client.ts
- test/client/api.client.unit.test.ts
- test/controller/certificates/check.details.controller.unit.test.ts
- test/utils/check.details.utils.unit.test.ts
* API client failing to compile as REST client interface has changed in
api-sdk-node.
> Fix compilation errors

- package-lock.json
- package.json
- src/client/api.client.ts
- test/client/api.client.unit.test.ts
* Change API clients for reading, updating certified certificates to use
new Result API.
Related:
[BI-10662](https://companieshouse.atlassian.net/browse/BI-10662)
> BI-10662 Change certs api clients to use new result iface

- src/views/certificates/llp-certificates/registered-office-options.html
- src/views/certificates/lp-certificates/principal-place-of-business-options.html
- src/views/certificates/registered-office-options.html
- test/controller/certificates/llp-certificates/registered.office.options.integration.test.ts
- test/controller/certificates/lp-certificates/principal.place.options.integration.test.ts
- test/controller/certificates/registered.office.options.integration.test.ts
* Automatically select current address on abridged page if option 3 or 4
selected on full page and user navigates back.
> BI-10849 Auto-select current addr on abridged page

- src/controllers/certificates/delivery.details.controller.ts
- src/controllers/certificates/delivery.options.controller.ts
- src/controllers/certificates/director.options.controller.ts
- src/controllers/certificates/options/OtherCompanyRedirectState.ts
- src/controllers/certificates/registered.office.options.controller.ts
- src/controllers/certificates/secretary.options.controller.ts
- src/model/page.urls.ts
- src/model/template.paths.ts
- src/routers/certificates/routers.ts
- src/views/delivery-options.html
- test/controller/certificates/delivery.details.controller.integration.test.ts
- test/controller/certificates/delivery.details.controller.unit.test.ts
- test/controller/certificates/delivery.options.controller.unit.test.ts
- test/controller/certificates/director.options.controller.integration.test.ts
- test/controller/certificates/options.controller.integration.test.ts
- test/controller/certificates/options/OtherCompanyOptionsMapper.unit.test.ts
- test/controller/certificates/registered.office.options.integration.test.ts
- test/controller/certificates/secretary.options.controller.integration.test.ts
Added delivery options page between certificate options page or selected cert options pages and the delivery details page. 
Resolves: BI-10997
> add delivery options page for certificate ordering

- Makefile
- package-lock.json
- package.json
- sonar-project.properties
> Adding sonar to this project

- src/controllers/certificates/delivery.options.controller.ts
- src/model/error.messages.ts
- src/views/delivery-options.html
- test/controller/certificates/delivery.options.controller.integration.test.ts
add validation to delivery options page to display an error prompting the user to select a delivery option
Resolves: BI-11186
> add error message for select a delivery option 

- src/controllers/certificates/delivery.options.controller.ts
- src/views/delivery-options.html
- test/controller/certificates/delivery.options.controller.integration.test.ts
add delivery_timescale patch request for certificate item, options are "standard" or "same-day"
Resolves: BI-11103
> add delivery option patch to certificate item add integration test

- src/controllers/certificates/email.options.controller.ts
- src/views/email-options.html
- test/controller/certificates/delivery.details.controller.integration.test.ts
BI-11193 Retain user selection on email options page
> BI-11193 retain email page selection

- src/model/error.messages.ts
- src/views/delivery-options.html
- test/controller/certificates/delivery.options.controller.integration.test.ts
- test/controller/certificates/email.options.controller.integration.test.ts
> BI-11338 - Wording amendments for same day certificate journey

- src/views/delivery-options.html
> BI-11354 - Update delivery options text

- src/views/certificates/check-details.html
- test/__mocks__/certificates.mocks.ts
- test/controller/certificates/check.details.controller.integration.test.ts
- test/controller/certificates/delivery.details.controller.unit.test.ts
add email copy required section for a dissolved cert check details page 
update tests
Resolves: BI-11224
> add email copy required section for a dissolved cert check details

- package-lock.json
- package.json
- src/client/api.client.ts
- test/client/api.client.unit.test.ts
- test/controller/certificates/check-details/DefaultCompanyCheckDetailsFactory.unit.test.ts
- test/controller/certificates/check-details/LLPCompanyCheckDetailsFactory.unit.test.ts
- test/controller/certificates/check-details/LPCompanyCheckDetailsFactory.unit.test.ts
- test/controller/certificates/check.details.controller.integration.test.ts
- test/controller/certificates/llp-certificates/check.details.controller.integration.test.ts
- test/controller/certificates/lp-certificates/check.details.controller.integration.test.ts
- test/controller/certified-copies/check.details.controller.integration.test.ts
- test/controller/missing-image-deliveries/check.details.controller.integration.test.ts
* Upcoming changes in api-sdk-node to rationalise item resources into a
single place.
Related: https://github.com/companieshouse/api-sdk-node/pull/423
> GCI-2166 Update classes to accommodate sdk model changes

- src/views/certificates/lp-certificates/index.html
> Update fee's section for LP company order a certificate start page

- src/controllers/certificates/check-details/LPCompanyCheckDetailsFactory.ts
- src/views/certificates/lp-certificates/check-details.html
- test/controller/certificates/check-details/LPCompanyCheckDetailsFactory.unit.test.ts
- test/controller/certificates/lp-certificates/check.details.controller.integration.test.ts
add email copy required section to lp check details page 
add email copy mapping 
update tests
Resolves: BI-11288
> add email copy required section to lp check details page

- src/controllers/certificates/delivery.options.controller.ts
> amended navigation issue from delivery options to principal options

- src/views/certified-copies/index.html
Amended fee text on certified document start page
BI-11007
> Amended text on certified document start page

- src/utils/check.details.utils.ts
- test/utils/check.details.utils.unit.test.ts
> BI-11006 - Add same day option to certified documents

- src/views/certified-copies/index.html
Amended text on certified documents start page
BI-11554
> Amended text on certified documents start page

- src/views/certified-copies/index.html
Added hyperlink back to more tab
BI-11554
> Added hyperlink back to more tab

- src/controllers/certified-copies/delivery.options.controller.ts
Amended standard delivery cost for incorporation company from 50 to 30
> changed standard delivery cost for incorporation company from 50 to 30

- src/controllers/certificates/delivery.options.controller.ts
- src/controllers/certified-copies/delivery.options.controller.ts
- test/controller/certificates/delivery.options.controller.integration.test.ts
- test/controller/certified-copies/delivery.options.controller.integration.test.ts
BI-11329 - Error message for delivery options page
> Error message for delivery options page

- gulpfile.js
- src/app.ts
- src/config/config.ts
- src/views/components/template.njk
- src/views/components/user-nav-bar.html
- src/views/layout.html
- static/app.scss
- static/js/mobile-menu.js
- test/setup.ts
* Copy over the approach developed by Ed in the search web app to this application and place the banner in the MID pages.
> BI-11519: Display sign in banner on MID pages

- static/app.scss
* Copy over Ed's sign in banner mobile background colour tweak from search web app to improve accessibility.
> BI-11519: Change background colour for accessibility

- src/controllers/certified-copies/delivery.options.controller.ts
- test/controller/certified-copies/delivery.options.controller.integration.test.ts
* Append certified copy item to basket if user is enrolled.
* User agent redirected to delivery details page if no deliverable items
already in basket otherwise redirected to basket page.
> GCI-2255 Append certified copy to basket if enrolled

- src/app.ts
attempt at stopping different user sign ins being over lapped by setting response headers
> attempt at stopping different user sign ins being over lapped

- src/app.ts
- src/controllers/error.controller.ts
- src/model/template.paths.ts
- src/views/error.html
Error page will now display should there be any http errors 
Banner on error page will also display a title which links to chs homepage
Resolves: BI-11755
> add error page

- src/controllers/certificates/check-details/CertificateTextMapper.ts
BI-11581-Update Check your orders page to include company name field
> Update Check your orders page to include company name field

- src/controllers/certificates/check-details/CertificateTextMapper.ts
- src/views/delivery-details.html
> BI-11801 - Update company name position in certificates web

- src/views/delivery-options.html
- test/controller/certificates/delivery.options.controller.integration.test.ts
- test/controller/certified-copies/delivery.options.controller.integration.test.ts
> BI-11835 - delivery details text changes

- src/views/certificates/index.html
Amended text on certificates start page
Bi-11836
> Amended text on certificates start page

- src/controllers/certificates/check-details/CertificateTextMapper.ts
- src/utils/check.details.utils.ts
- src/views/certificates/check-details-alternate.html
- src/views/certificates/check-details.html
- src/views/certificates/llp-certificates/check-details-alternate.html
- src/views/certificates/llp-certificates/check-details.html
- src/views/certificates/lp-certificates/check-details-alternate.html
- src/views/certificates/lp-certificates/check-details.html
- src/views/certified-copies/check-details.html
- test/controller/certificates/check-details/CertificateTextMapper.unit.test.ts
- test/controller/certificates/check.details.controller.integration.test.ts
- test/controller/certificates/llp-certificates/check.details.controller.integration.test.ts
- test/controller/certificates/lp-certificates/check.details.controller.integration.test.ts
- test/controller/certified-copies/check.details.controller.integration.test.ts
- test/utils/check.details.utils.unit.test.ts
> BI-11843 -Update check details

- src/views/certificates/index.html
- src/views/certificates/llp-certificates/index.html
- src/views/certificates/lp-certificates/index.html
Text amendments for LLP and LP certificates start pages
Resolves BI-11836
> Text amendments for LLP and LP certificates start pages

- src/views/certified-copies/index.html
Amendment to certified copy start page fees text
Resolves BI-11849
> Amendment to certified copy start page fees text

- src/views/certified-copies/index.html
Amendment to include missing line on certified documents start page
BI-11849
> Amendment to include missed text

- src/controllers/certificates/delivery.options.controller.ts
- src/controllers/certified-copies/delivery.options.controller.ts
- src/views/delivery-options.html
> BI-11850 - Update dispatch text for express certified document orders

- src/views/certified-copies/index.html
Text amendment on certified documents start page.
BI-11948
> Text amendment on certified documents start page.

- src/controllers/certificates/check-details/CertificateTextMapper.ts
- src/views/certificates/check-details-alternate.html
- test/controller/certificates/check.details.controller.integration.test.ts
BI-11881 - Update Check your certificate page
> Update Check your certificate page

- src/controllers/certificates/check-details/CertificateTextMapper.ts
- src/controllers/certificates/check-details/DefaultCertificateMappable.ts
- src/controllers/certificates/check-details/DefaultCompanyCheckDetailsFactory.ts
- src/controllers/certificates/check-details/LLPCheckDetailsFactory.ts
- src/controllers/certificates/check-details/LPCompanyCheckDetailsFactory.ts
- test/controller/certificates/check-details/CertificateTextMapper.unit.test.ts
- test/utils/check.details.utils.unit.test.ts
BI-11881 - Update "Check your certificate" page
> Amendments to retain description for check details page dispatch method to match prototype.

- src/views/certificates/check-details-alternate.html
Amendment to add matomo reporting to check details from basket
BI-11876
> Amendment to add matomo reporting to check details from basket

- src/config/config.ts
- src/controllers/certificates/delivery.options.controller.ts
- src/controllers/certificates/director.options.controller.ts
- src/controllers/certificates/email.options.controller.ts
- src/controllers/certificates/home.controller.ts
- src/controllers/certificates/llp-certificates/designated-members.options.controller.ts
- src/controllers/certificates/llp-certificates/members.options.controller.ts
- src/controllers/certificates/llp-certificates/registered.office.options.controller.ts
- src/controllers/certificates/lp-certificates/principal.place.options.controller.ts
- src/controllers/certificates/options/OptionsController.ts
- src/controllers/certificates/options/OptionsViewModel.ts
- src/controllers/certificates/registered.office.options.controller.ts
- src/controllers/certificates/secretary.options.controller.ts
- src/model/BasketLink.ts
- src/utils/basket.utils.ts
- src/views/components/user-nav-bar.html
- test/__mocks__/redis.mocks.ts
- test/controller/certificates/delivery.options.controller.integration.test.ts
- test/controller/certificates/director.options.controller.integration.test.ts
- test/controller/certificates/email.options.controller.integration.test.ts
- test/controller/certificates/llp-certificates/designated-member.options.controller.integration.test.ts
- test/controller/certificates/llp-certificates/members.options.controller.integration.test.ts
- test/controller/certificates/llp-certificates/options.controller.integration.test.ts
- test/controller/certificates/llp-certificates/registered.office.options.integration.test.ts
- test/controller/certificates/lp-certificates/options.controller.integration.test.ts
- test/controller/certificates/lp-certificates/principal.place.options.integration.test.ts
- test/controller/certificates/options.controller.integration.test.ts
- test/controller/certificates/registered.office.options.integration.test.ts
- test/controller/certificates/secretary.options.controller.integration.test.ts
- test/utils/basket.utils.test.ts
> Add basket link to pre basket certificate journeys

- src/controllers/missing-image-deliveries/check.details.controller.ts
- src/controllers/missing-image-deliveries/home.controller.ts
- test/controller/missing-image-deliveries/home.controller.integration.test.ts
> Add basket links for MID journey

- src/controllers/certified-copies/delivery.options.controller.ts
- src/controllers/certified-copies/home.controller.ts
- test/controller/certified-copies/delivery.options.controller.integration.test.ts
- test/controller/certified-copies/home.controller.integration.test.ts
> Add basket link to certicates web certified document screens

- src/controllers/certificates/StaticRedirectCallback.ts
- src/controllers/certificates/delivery.options.controller.ts
- src/controllers/certificates/email.options.controller.ts
- src/controllers/certified-copies/delivery.options.controller.ts
- test/__mocks__/certificates.mocks.ts
- test/controller/certificates/StaticRedirectCallback.unit.test.ts
- test/controller/certificates/delivery.options.controller.integration.test.ts
- test/controller/certificates/email.options.controller.integration.test.ts
- test/controller/certified-copies/delivery.options.controller.integration.test.ts
> BI-12126 - Delivery details redirect

- src/controllers/missing-image-deliveries/home.controller.ts
- src/views/missing-image-deliveries/index.html
- test/controller/missing-image-deliveries/home.controller.integration.test.ts
> BI-12135 - Add warning message for a full basket at start of mid journey

- src/controllers/missing-image-deliveries/home.controller.ts
- src/views/missing-image-deliveries/index.html
- Prevent error appearing for non signed in users
- Disable button on error
> Disable button and prevent error when user not signed in

- .gitignore
- .mocharc.json
- .nycrc.json
- Makefile
- package-lock.json
- package.json
- sonar-project.properties
Resolves: GCI-2132
Certificates web will now display the percentage of code coverage
> GCI-2132 - Configure certificates web to show test coverage percentage in sonar

- src/views/components/footer/template.njk
BI-11974 - Add feedback links to certificates orders web pages
> Added feedback div to the footer template

- gulpfile.js
- package-lock.json
- package.json
- Eliminates high and critical vulnerabilities
- Eliminates build errors/warnings
- Refactors Gulp file
> Feature/CC-1133: Resolve high + critical vulnerabilities

- package-lock.json
- src/views/certificates/index.html
- src/views/certificates/llp-certificates/index.html
- src/views/certificates/lp-certificates/index.html
- src/views/certificates/options.html
- src/views/certified-copies/index.html
- test/controller/certificates/options.controller.integration.test.ts
Fulfils [BI-13600](https://companieshouse.atlassian.net/browse/BI-13600)
[BI-13600]: https://companieshouse.atlassian.net/browse/BI-13600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BI-13600 - Change wording of content for incorporation packages and certificate of good standing in CHS

- src/views/certificates/check-details-alternate.html
- src/views/certificates/check-details.html
- src/views/certificates/llp-certificates/check-details-alternate.html
- src/views/certificates/llp-certificates/check-details.html
- src/views/certificates/llp-certificates/options.html
- src/views/certificates/lp-certificates/check-details-alternate.html
- src/views/certificates/lp-certificates/check-details.html
- src/views/certificates/lp-certificates/options.html
- test/controller/certificates/check.details.controller.integration.test.ts
- test/controller/certificates/home.controller.integration.test.ts
- test/controller/certificates/llp-certificates/check.details.controller.integration.test.ts
- test/controller/certificates/llp-certificates/options.controller.integration.test.ts
- test/controller/certificates/lp-certificates/check.details.controller.integration.test.ts
- Extra web pages have been found which contained outdated 'statement of good standing'- criteria of BI-13600 updated and text changes added to reflect this 
- Tests also updated
> BI-13600 - Further text changes where 'statement of good standing' was found

- package-lock.json
> BI-10900 - api-enumerations submodule bump

- src/views/certificates/llp-certificates/index.html
- src/views/certificates/lp-certificates/index.html
- test/controller/certificates/home.controller.integration.test.ts
BI-13976:update lp-certificates and llp-certificates start page to remove of incorporation
> update lp-certificates and llp-certificates start page to remove of incorporation

- src/views/certificates/index.html
- src/views/certificates/llp-certificates/index.html
- src/views/certificates/lp-certificates/index.html
- test/controller/certificates/home.controller.integration.test.ts
BI-12032:update order certificate page
> Bi 12032 update order certificate page

- src/views/certificates/index.html
- src/views/certificates/llp-certificates/index.html
- src/views/certificates/lp-certificates/index.html
BI-12032:Fix misalignment in costs table
> Fix misalignment in costs table

- src/views/certificates/index.html
- src/views/certificates/llp-certificates/index.html
- src/views/certificates/lp-certificates/index.html
BI-12032:Increase font-size of company name and add omitted texts in LP and LLP
> Increase font-size of company name and add omitted texts in LP and LLP

- src/controllers/certificates/additional.copies.controller.ts
- src/model/error.messages.ts
- src/views/additional-copies.html
- test/controller/certificates/additional.copies.options.controller.integration.test.ts
- Add validation and tests for additional copies options page
- Fulfils [BI-14021](https://companieshouse.atlassian.net/browse/BI-14021)
[BI-14021]: https://companieshouse.atlassian.net/browse/BI-14021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BI-14021 - Add validation to Would you like additional copies page

- src/controllers/certificates/check-details/DefaultCompanyCheckDetailsFactory.ts
- src/views/certificates/check-details-alternate.html
- test/controller/certificates/check-details/DefaultCompanyCheckDetailsFactory.unit.test.ts
Resolves [BI-12033](https://companieshouse.atlassian.net/browse/BI-12033)
Add quantity to check your certificate page to support new additional copies page
[BI-12033]: https://companieshouse.atlassian.net/browse/BI-12033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add quantity to view change options page

- src/views/certificates/index.html
- src/views/certificates/llp-certificates/index.html
- src/views/certificates/lp-certificates/index.html
- src/views/certified-copies/index.html
- src/views/missing-image-deliveries/index.html
fixing banner warning that the users basket is full
> Bi 6926 basketfull warning bugfix

- src/views/certificates/index.html
- src/views/certificates/llp-certificates/index.html
- src/views/certificates/lp-certificates/index.html
Reverting additional check as causes additional issues that will require addressing.
> Revert check for error

- Makefile
Fix sonar target in Makefile to run Sonar analysis
> Fix sonar target in Makefile to run analysis on pipeline

- package-lock.json
- package.json
Same security fixes as before, without express bump due to flashing bug
> CC-593: security fixes without express bump

- terraform/groups/ecs-service/profiles/development-eu-west-2/rebel1/vars
Part of MVP for smoke testing mongo:7
> Add web certificates orders to rebel1

- src/app.ts
- src/config/config.ts
https://companieshouse.atlassian.net/browse/ASM-474
Exclude healthcheck route.
> Exclude healthcheck middleware route

- src/app.ts
- src/config/config.ts
Reverts companieshouse/certificates.orders.web.ch.gov.uk#429
> Revert "ASM-474 - Add explicit session middleware paths"
