companieshouse/certificates.orders.web.ch.gov.uk

Makefile

This change will allow any future tests to be easily added to the Makefile (for example if you would like to add integration tests).

Tweak makefile to use test-unit

---

package-lock.json
src/controllers/check.details.controller.ts
src/test/controllers/check.details.controller.spec.unit.ts

When not provided registered office address is `undefined` rather than an empty string

Fix for registered office address always appearing

---

src/views/layout.html

When displayed on an IOS device numbers such as the company number on the check details screen are showing as phone numbers. This PR fixes the issue.

Add fix for company numbers displaying as phone numbers on ios devices

---

src/app.ts
src/config/config.ts
src/controllers/certified-copies/home.controller.ts
src/views/layout.html

Adds ability to include either a `Order a certificate` or  a `Order a certified document` service name in the service header.

Fix/GCI-860: Add functionality to switch between both service names

---

src/app.ts

Add missing service name  import: `SERVICE_NAME_GENERIC`

Fix/GCI-860: Add missing service name  import

---

src/views/certified-copies/check-details.html

Removes the links for "deleting a document"

Feature/GCI-1228: Delete the  the 'remove document' calls-to-action

---

package.json

Change `package.json` to link to most recent commit hash for ch-sdk-node.

Chore/GCI-1279: Update commit hash for ch-sdk-node version

---

src/controllers/certificates/home.controller.ts
src/model/template.paths.ts
src/views/error-pages/you-cannot-use-this-service.html
test/controller/certificates/home.controller.integration.test.ts

Add error view 
Update controller to redirect to error page 
Update test
Resolves: GCI-1295

Display error page if company should not be able to order a certificate in the node app

---

src/views/certificates/check-details.html

Google lighthouse accessibility report produced the following message:
`<dl>'s do not contain only properly-ordered <dt> and <dd> groups, <script>, <template> or <div> elements.`
This was due to where actions were not present `span` elements were added. This is flagged by lighthouse as a `dl` should not contain a span.
Blank actions allow the span to be placed inside a `dd` element.
Resolves: GCI-1350

Add blank actions to fix google lighthouse accessibility issue

---

package-lock.json
package.json
src/app.ts
src/middleware/auth.middleware.ts
src/middleware/certificates/auth.middleware.ts
src/middleware/certified-copies/auth.middleware.ts
src/middleware/missing-image-deliveries/auth.middleware.ts
src/session/helper.ts
test/__mocks__/redis.mocks.ts
test/controller/certificates/check.details.controller.integration.test.ts
test/controller/certificates/check.details.controller.unit.test.ts
test/controller/certificates/options.controller.unit.test.ts
test/controller/certified-copies/check.details.controller.integration.test.ts
test/middleware/auth.middleware.unit.test.ts
test/middleware/certificates/auth.middleware.unit.test.ts
test/middleware/certified-copies/auth.middleware.unit.test.ts
test/middleware/missing-image-deliveries/auth.middleware.unit.test.ts
test/utils/check.details.utils.unit.test.ts

Updated version of ch session handler by importing the npm repo of the ch session handler, no longer using the git repo.
Resolves: BI-6119

use ch npm for ch session handler import and usage

---

src/controllers/certificates/delivery.details.controller.ts
test/controller/certificates/delivery.details.controller.integration.test.ts
test/controller/certificates/delivery.details.controller.unit.test.ts

Determines if the back button should take the user to the cert option page or the registered office options page when ordering a certificate.
Resolves: BI-6028

add logic for back button delivery details page 

---

src/controllers/certificates/options.controller.ts
src/controllers/certificates/registered.office.options.controller.ts
src/views/certificates/registered-office-options.html
test/controller/certificates/options.controller.unit.test.ts

Reverted radio button retention on reg office details page. This allows for retention of the reg office option on the main options page to display when a user goes backwards through the journey.
Resolves: BI-6395

revert radio button option retention implement default reg office option

---

src/controllers/certificates/director.options.controller.ts
src/views/certificates/director-options.html
test/controller/certificates/director.options.controller.integration.test.ts

If a user revisits the directors option page, any option that they previously selected will show as checked.
Resolves: BI-6451

Retains previously selected director option and checks checkbox

---

src/controllers/certificates/options.controller.ts

When a user returns to the page after selecting the options in the directors screen and then removes the option in the options page, the options selected would remain. Adding the following allows for a clean slate on starting the order again.
Resolves: BI-6017

Update set items so that all fields are covered in the initial item for directors

---

src/controllers/certificates/secretary.options.controller.ts

Removed unused options in setting up initial secretary options as these options were persisting if s customer selected and then unselected the secretary options.
Resolves: BI-6203

remove unused initial sec options

---

src/controllers/certificates/secretary.options.controller.ts
src/views/certificates/secretary-options.html
test/controller/certificates/secretary.options.controller.integration.test.ts

Retains a user's previously selected checkboxes on the secretary options page and displays those chosen options if a user revisits that page.
Resolves: BI-6452

Bi 6452 retain secretary option checked boxes

---

src/utils/check.details.utils.ts
test/controller/certified-copies/check.details.controller.integration.test.ts
test/utils/check.details.utils.unit.test.ts

Add config dispatch time date to delivery method section on the check your order details page within the cert copies journey
Resolves: BI-7359

add configurable dispatch time update tests

---

src/controllers/certificates/home.controller.ts
src/views/certificates/index.html
test/controller/certified-copies/check.details.controller.integration.test.ts
test/utils/check.details.utils.unit.test.ts

Use configurable dispatch date to output processing time on certs and dissolved certs start now page
Resolves: BI-7073

add config dispatch date update text on cert start now page

---

package-lock.json
package.json
src/controllers/certificates/home.controller.ts
src/controllers/certified-copies/home.controller.ts
src/controllers/missing-image-deliveries/home.controller.ts
src/views/certificates/index.html
src/views/certified-copies/index.html
src/views/layout.html
src/views/missing-image-deliveries/index.html
test/controller/certificates/home.controller.integration.test.ts
test/controller/certified-copies/home.controller.integration.test.ts
test/controller/missing-image-deliveries/home.controller.integration.test.ts

Increment frontend kit package version
Update home controllers to pass company name to templates
Add notification banners to each start now page and display company name and company number
Update home page integration tests
Resolves: BI-1852 BI-1853 BI-1854

Add notification banners to all start now pages to show company in context

---

src/controllers/certificates/llp-certificates/options.controller.ts
src/controllers/certificates/options.controller.ts
test/controller/certificates/llp-certificates/options.controller.integration.test.ts
test/controller/certificates/options.controller.integration.test.ts

- Bypasses calls to companyProfile in the options controllers for default and LLP company types.
- Instead, uses companyStatus off of the certificateItem
[BI-9890](https://companieshouse.atlassian.net/browse/BI-9890)

BI-9890 Options controller bypass company profile

---

src/views/components/footer/template.njk

BI-9825 Direct users to GOV.UK contact page - Missing image delivery

little change to exclude other links from stating opens opens in new tab

---

src/controllers/certificates/check.details.controller.ts
src/controllers/certificates/llp-certificates/check.details.controller.ts
test/controller/certificates/check.details.controller.unit.test.ts
test/controller/certificates/llp-certificates/check.details.controller.unit.test.ts

* Add extra line break where directors, secretaries or members options
have been chosen to make text consistent with confirmation page.

Add extra line break to check details opts

---

src/controllers/certificates/director.options.controller.ts
src/controllers/certificates/llp-certificates/designated-members.options.controller.ts
src/controllers/certificates/llp-certificates/registered.office.options.controller.ts
src/controllers/certificates/registered.office.options.controller.ts

* ROA, directors and designated members controllers were not checking includeBasicInformation on the patched item's
* item options when determining which page to redirect to.
* Tested locally, works fine.

Fix bug where includeBasicInformation was not checked

---

src/controllers/certificates/options/AbstractOptionsMapper.ts
src/controllers/certificates/options/LLPOptionsMapper.ts
src/controllers/certificates/options/LLPRedirectState.ts
src/controllers/certificates/options/LLPRedirectStateMachine.ts
src/controllers/certificates/options/LPOptionsMapper.ts
src/controllers/certificates/options/LPRedirectState.ts
src/controllers/certificates/options/LPRedirectStateMachine.ts
src/controllers/certificates/options/OptionsControllerConfiguration.ts
src/controllers/certificates/options/OptionsPageRedirect.ts
src/controllers/certificates/options/OptionsService.ts
src/controllers/certificates/options/OtherCompanyOptionsMapper.ts
src/controllers/certificates/options/OtherCompanyRedirectState.ts
src/controllers/certificates/options/OtherCompanyRedirectStateMachine.ts
src/controllers/certificates/options/RedirectState.ts
src/controllers/certificates/options/RedirectStateMachine.ts
test/controller/certificates/options/LLPOptionsMapper.unit.test.ts
test/controller/certificates/options/LPOptionsMapper.unit.test.ts
test/controller/certificates/options/OptionsService.unit.test.ts
test/controller/certificates/options/OtherCompanyOptionsMapper.unit.test.ts

* Use template method/state pattern to determine a redirect on the
options page for LLP/LP/other company types for the provided options.
* Set ROA/PPB include_address_records_type to current by default if
selected on options page.
Resolves:
[BI-10811](https://companieshouse.atlassian.net/browse/BI-10811)

BI-10811 Rework options page redirects

---

Makefile
package-lock.json
package.json
sonar-project.properties

* Trying to migrate Concourse build from Node 10 to Node 14 in the hope that this will make it easier to upgrade to recent versions of dependencies like `node-sass` with fewer (so far known) security vulnerabilities as suggested by dependabot.
* As there is no `build-unit-test` task available for Node 14, forced to use roughly equivalent `build-test-analyse` task for Node 14.
* This however includes a Sonar scan as part of the job.
* This PR provides the necessary configuration for the scan.
* Tested on the Concourse Sandbox:
* [BEFORE](https://ci.sandbox.aws.chdev.org/teams/development/pipelines/certificates.orders.web.ch.gov.uk/jobs/build-test-analyse/builds/1#L62445ff8:1300)
* [AFTER](https://ci.sandbox.aws.chdev.org/teams/development/pipelines/certificates.orders.web.ch.gov.uk/jobs/bui …

GCI-2065: Configure SonarQube to facilitate Node 14 build in Concourse

---

src/controllers/certificates/delivery.options.controller.ts
src/views/delivery-options.html
test/controller/certificates/delivery.details.controller.integration.test.ts
test/controller/certificates/delivery.options.controller.integration.test.ts

pass deliveryTimescale value to delivery options template
display the previously selected value on the delivery option page
add test for displaying of the checked delivery option
move back button tests from delivery details to delivery options as delivery options page is now before delivery details in the journey
Resolves : BI-11192

display previously selected delivery option value

---

src/controllers/certificates/delivery.details.controller.ts

remove the hardcoded standard delivery selection from the delivery details patching the certificate item

stop defaulting to standard delivery via patch in delivery details

---

src/middleware/certificates/auth.middleware.ts

- This is an attempt to have an impact on the security vulnerabilities reported by SonarQube.
- Unfortunately, it only seems to update these when changes are merged to `master`?

GCI-2122: Try limiting originating URL in all cases

---

src/controllers/certificates/delivery.options.controller.ts

There is a scenario where the user selects express delivery and wants an email copy but then navigates backwards in the journey and now selects standard delivery.  As the api will not allow an email copy selected along with standard delivery this pr clears out the email copy selection if the delivery option is standard in the patch.
Resolves: BI-11192

update delivery option patch

---

src/controllers/certificates/delivery.details.controller.ts

set standard delivery in patch for dissolved cert to allow output on check details page, this is temporary as upcoming work will allow this to also be set to same-day

set standard delivery in patch for dissolved cert

---

src/middleware/certificates/auth.middleware.ts
test/middleware/certificates/auth.middleware.unit.test.ts

- This is an attempt to have an impact on the security vulnerabilities reported by SonarQube.
- Unfortunately, it only seems to update these when changes are merged to `master`?
- By prefixing the return to  URL with the value of `CHS_URL`, we may be apparently leaving the redirect less open to being pointed at untrusted sites?

GCI-2122: Try prefixing return to URL with CHS URL

---

package-lock.json
package.json
src/client/api.client.ts
src/controllers/certificates/StaticRedirectCallback.ts
src/controllers/certificates/delivery.options.controller.ts
src/controllers/certificates/email.options.controller.ts
test/client/api.client.unit.test.ts
test/controller/certificates/StaticRedirectCallback.unit.test.ts
test/controller/certificates/delivery.options.controller.integration.test.ts
test/controller/certificates/email.options.controller.integration.test.ts

* Delivery and email options controllers now call new appendItemToBasket endpoint
if user enrolled for multi-item basket and basket already contains
deliverable items.
* User agent redirected to global delivery details page when
continuing from delivery options or email options pages and no
deliverable items in basket.
* User agent redirected to basket page when continuing from delivery
options or email options pages and deliverable items already in
basket.
Resolves:
[GCI-2157](https://companieshouse.atlassian.net/browse/GCI-2157)

GCI-2157 conditional redirects for certificates journey

---

static/js/mobile-menu.js

* The jQuery `$` version returns some complex wrapping object for the element, the `document.querySelector` version just returns the targeted element.
* However, I don't know why the former seems to work in this case, whilst the latter seems not to work.

BI-11519: jQuery $ allows click() callback to be set correctly?

---

src/middleware/certificates/auth.middleware.ts
src/middleware/certified-copies/auth.middleware.ts
src/utils/request.util.ts
test/middleware/certificates/auth.middleware.unit.test.ts
test/middleware/certified-copies/auth.middleware.unit.test.ts
test/utils/request.util.unit.test.ts

add correct redirect for dissolved certs and cert copies to delivery options page add urls to whitelist update tests
Resolves: BI-11697

add correct redirect for dissolved certs and cert copies

---

src/controllers/certificates/delivery.details.controller.ts
src/controllers/certificates/llp-certificates/delivery.details.controller.ts
src/controllers/certificates/lp-certificates/delivery.details.controller.ts
src/controllers/certified-copies/delivery.details.controller.ts
src/views/delivery-details.html
test/controller/certified-copies/delivery.details.controller.integration.test.ts

* Revert the bug fix for GCI-2318, implemented earlier precisely to exclude this field from the page for certified copies.
* Plumb company name into the certified copies delivery details controller.
**This PR must not be merged until the story is brought into the sprint.**

BI-11726: Introduce company name to certified copies delivery page

---

src/utils/check.details.utils.ts
test/utils/check.details.utils.unit.test.ts

* **This PR must be merged to master only once [BI-11726](https://github.com/companieshouse/certificates.orders.web.ch.gov.uk/pull/310) has been merged to master.**
* Note for clarity it is currently being compared with the [bi-11726-add-company-name-to-delivery-page](https://github.com/companieshouse/certificates.orders.web.ch.gov.uk/tree/bi-11726-add-company-name-to-delivery-page) branch.

BI-11727: Add company name to check your order details page

---

package-lock.json
package.json

* Update the application's dependency on `api-sdk-node` to bring in [this fix](https://github.com/companieshouse/api-sdk-node/pull/593).
This PR merges "back" to `feature/ecs-service-2` as work will continue on that branch to cover later deployments to `staging` and `live`, and having this change on `feature/ecs-service-2` should at least make it possible to test the bug fix on `cidev` for now.

CC-605: Update dependency to bring in fix

---

terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars

* Turn the logging level in `live` from `debug` back down to `info`, as the issue CC-750 has now been fixed in `live`.  
This reverts commit e38325e861deeec31727fdf34cfa3b60503619d4.

CC-750: Turn logging level back down to info in live

---

src/views/certificates/index.html
test/controller/certificates/home.controller.integration.test.ts

BI-13976:Update Certificate start page to remove "of incorporation" from certificate content

Update Certificate start page to remove "of incorporation" from certificate content

---

src/controllers/certificates/additional.copies.quantity.controller.ts
test/controller/certificates/additional.copes.quantity.controller.integration.test.ts

Resolves [GCI-2582] (https://companieshouse.atlassian.net/browse/GCI-2582)
Update patch so that the additional copies number chosen by is appended to initial quantity to avoid incorrect quantity calculation.
e.g  Initial quantity is always 1 so if user chooses 3 copies , then total quantity should be 4. 
[GCI-2582]: https://companieshouse.atlassian.net/browse/GCI-2582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GCI-2582- Resolve incorrect quantity set for additional-copies

---

terraform/groups/ecs-service/main.tf
terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
terraform/groups/ecs-service/profiles/development-eu-west-2/phoenix1/vars
terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
terraform/groups/ecs-service/variables.tf

Update modules to latest version, configure target cpu for scaling to 80% instead of 50%. Also added scale down and up. CPU and memory metrics look ok in aws for the different environments.

add scaledown, target cpu scaling, and update modules

---

src/controllers/certificates/additional.copies.controller.ts
src/controllers/certificates/delivery.options.controller.ts
test/controller/certificates/delivery.options.controller.integration.test.ts

Resolves [BI-13999](https://companieshouse.atlassian.net/browse/BI-13999) 
- Add changes for standard delivery option page to direct to additional copies
- Ensure back link redirects to correct page depending on delivery option choses (e.g no email option for standard_) 
- Edit tests to support new journey flow. 
[BI-13999]: https://companieshouse.atlassian.net/browse/BI-13999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BI-13999-add changes for standard delivery option to direct to additional copies

---

src/controllers/certificates/check-details/LLPCheckDetailsFactory.ts
src/controllers/certificates/check-details/LPCompanyCheckDetailsFactory.ts
src/views/certificates/check-details-alternate.html
src/views/certificates/llp-certificates/check-details-alternate.html
src/views/certificates/lp-certificates/check-details-alternate.html
test/controller/certificates/check-details/LLPCompanyCheckDetailsFactory.unit.test.ts
test/controller/certificates/check-details/LPCompanyCheckDetailsFactory.unit.test.ts

Resolves [BI-12033](https://companieshouse.atlassian.net/browse/BI-12033)
Following Wayne's observations in test (see ticket) -adding missing quantity field to check certificate pages for LL, LLP and dissolved companies
[BI-12033]: https://companieshouse.atlassian.net/browse/BI-12033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BI-12033 Add quantity to LLP,LP and dissolved check certificate pages

---

src/controllers/certificates/additional.copies.controller.ts
src/controllers/certificates/additional.copies.quantity.controller.ts
test/controller/certificates/additional.copies.options.controller.integration.test.ts

Resolves [GCI-2589](https://companieshouse.atlassian.net/browse/GCI-2589)
Change Additional Quantity Controller to set a base quantity each time the user navigates back to the this page via the browser's back button.
Also change Additional Quantity option page (yes or no) so that if the user has picked additional quantities before and navigate back via back button and they pick 'no' the quantity will reset to 1. 
This should ensure that the amount of additional copies/certificates is not added on to the quantity total previously chosen and is now patched correctly with the new quantity. 
[GCI-2589]: https://companieshouse.atlassian.net/browse/GCI-2589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GCI-2580- prevent incorrect quantity when using the browser back button

---

src/views/certificates/index.html
src/views/certificates/llp-certificates/index.html
src/views/certificates/lp-certificates/index.html

Prevent the notification being present while the basket error is displayed and update style to reflect how the notification looked previously.
Resolves: GCI-2586

GCI-2586 - Remove notification on error and update notification style

---

src/views/certificates/index.html
src/views/certificates/llp-certificates/index.html
src/views/certificates/lp-certificates/index.html

Resolves: [GCI-2593](https://companieshouse.atlassian.net/browse/GCI-2593) and [GCI-2594](https://companieshouse.atlassian.net/browse/GCI-2594)
[GCI-2593]: https://companieshouse.atlassian.net/browse/GCI-2593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GCI-2594]: https://companieshouse.atlassian.net/browse/GCI-2594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GCI-2593:fix conflict between warning and error messages showing at the same time and also fix register link going to live link
